/*
 almond 0.3.1 Copyright (c) 2011-2014, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/almond for details
 twgl.js 1.9.0 Copyright (c) 2015, Gregg Tavares All Rights Reserved.
 Available via the MIT license.
 see: http://github.com/greggman/twgl.js for details
*/
var Danza=function(d,n){this.audioCtx=new (window.AudioContext||window.webkitAudioContext);this.analyser=this.audioCtx.createAnalyser();this.analyser.fftSize=d||2048;this.bufferLength=this.analyser.frequencyBinCount;n||this.analyser.connect(this.audioCtx.destination);this.data=new Uint8Array(this.bufferLength);this.keys=new Uint8Array(this.bufferLength);this.notes=new Uint16Array(160);this.thresholds=new Uint8Array(160);this.weights=new Uint8Array(160);for(var l=0,a=this.audioCtx.sampleRate/2/this.bufferLength;l<
this.bufferLength;l++){var w=this.freq2midi((l+.5)*a);this.keys[l]=w;this.weights[w]++}this.count=1};Danza.prototype.listen=function(d){this.el=d;this.source&&this.source.disconnect(this.analyser);this.source=this.audioCtx.createMediaElementSource(d);this.source.connect(this.analyser)};
Danza.prototype.spawn=function(d){var n={from:1,to:128,snap:.66,smooth:[.33,.33,.33,.33]};if(d)for(var l in n)d[l]||(d[l]=n[l]);else d=n;var a=this,w=d,t=new Float32Array(4);return function(d,g){function h(c,e,f){c=c?c:0;f=Math.min(f,w.snap);0>f&&(f=c>e?Math.abs(w.snap):-f);return f*c+(1-f)*e}if(g)for(var b in w)void 0!==g[b]&&(w[b]=g[b]);g=w;if(g.count===a.count)return t;b=g.smooth;for(var u=-1,x=0,l=0,q=0,A=0,e=0,c=g.from;c<g.to;c++){var f=a.notes[c];f>a.thresholds[c]&&(q+=f-128,A+=c%12,l+=c,e++,
f>x&&(u=c,x=f))}t[0]=h(u%12/12,t[0],b[0]);t[1]=h((e?A/e:0)/12,t[1],b[1]);t[2]=h(((e?l/e:0)-g.from)/(g.to-g.from),t[2],b[2]);t[3]=h((e?q/e:0)/128,t[3],b[3]);g.count=a.count++;return t}};
Danza.prototype.update=function(){this.analyser.getByteFrequencyData(this.data);for(var d=0;d<this.notes.length;d++)this.notes[d]=0;for(d=0;d<this.keys.length;d++)this.notes[this.keys[d]]+=this.data[d];for(d=0;d<this.notes.length;d++)this.notes[d]/=this.weights[d],this.thresholds[d]=128+Math.max(.66*Math.max(0,this.notes[d]-128),this.thresholds[d]),128<this.thresholds[d]&&this.thresholds[d]--};
Danza.prototype.freq2midi=function(d){d=eval(d);var n=523.251,l=4,a=0,w=0,t=1,M=0,g=0,h=0,b=72;for(tableau=[];d<n;)n=Math.floor(1E3*n/1.05946309436)/1E3,w+=1,a=-1,h=1,M=n;for(;d>n;)n=Math.floor(1059.46309436*n)/1E3,--w,a=1,g=n;Math.abs(d-M)<Math.abs(d-g)?(a=-1,w+=1):1==h&&(a=-1);0==M&&(M=Math.floor(1E3*n/1.05946309436)/1E3,Math.abs(d-M)<Math.abs(d-g)&&(w+=1,a=1));for(w=Math.abs(w);0!=w;){if(1==t&&-1==a||12==t&&1==a)l+=eval(a),1==a&&(t=0),-1==a&&(t=13);t+=a;b+=a;--w}return b};
!function(d,n){"function"==typeof define&&define.amd&&define([],n);"undefined"!=typeof module&&module.exports?module.exports=n():d.twgl=n()}(this,function(){var d,n,l;return function(a){function w(r,c){var e,q,h,b,a,t,D,H,O,A=c&&c.split("/"),g=f.map,K=g&&g["*"]||{};if(r&&"."===r.charAt(0))if(c){r=r.split("/");a=r.length-1;f.nodeIdCompat&&L.test(r[a])&&(r[a]=r[a].replace(L,""));r=A.slice(0,A.length-1).concat(r);for(a=0;a<r.length;a+=1)if(e=r[a],"."===e)r.splice(a,1),--a;else if(".."===e){if(1===a&&
(".."===r[2]||".."===r[0]))break;0<a&&(r.splice(a-1,2),a-=2)}r=r.join("/")}else 0===r.indexOf("./")&&(r=r.substring(2));if((A||K)&&g){e=r.split("/");for(a=e.length;0<a;--a){if(q=e.slice(0,a).join("/"),A)for(O=A.length;0<O;--O)if(h=g[A.slice(0,O).join("/")],h&&(h=h[q])){b=h;t=a;break}if(b)break;!D&&K&&K[q]&&(D=K[q],H=a)}!b&&D&&(b=D,t=H);b&&(e.splice(0,t,b),r=e.join("/"))}return r}function t(c,e){return function(){var f=I.call(arguments,0);return"string"!=typeof f[0]&&1===f.length&&f.push(null),C.apply(a,
f.concat([c,e]))}}function M(c){return function(e){return w(e,c)}}function g(c){return function(f){e[c]=f}}function h(r){if(E.call(c,r)){var f=c[r];delete c[r];y[r]=!0;x.apply(a,f)}if(!E.call(e,r)&&!E.call(y,r))throw Error("No "+r);return e[r]}function b(c){var e,f=c?c.indexOf("!"):-1;return-1<f&&(e=c.substring(0,f),c=c.substring(f+1,c.length)),[e,c]}function u(c){return function(){return f&&f.config&&f.config[c]||{}}}var x,C,q,A,e={},c={},f={},y={},E=Object.prototype.hasOwnProperty,I=[].slice,L=
/\.js$/;q=function(c,e){var f,a=b(c),q=a[0];return c=a[1],q&&(q=w(q,e),f=h(q)),q?c=f&&f.normalize?f.normalize(c,M(e)):w(c,e):(c=w(c,e),a=b(c),q=a[0],c=a[1],q&&(f=h(q))),{f:q?q+"!"+c:c,n:c,pr:q,p:f}};A={notrequirebecasebrowserifymessesup:function(c){return t(c)},exports:function(c){var f=e[c];return"undefined"!=typeof f?f:e[c]={}},module:function(c){return{id:c,uri:"",exports:e[c],config:u(c)}}};x=function(f,b,d,m){var u,w,x,l,D,H=[];l=typeof d;if(m=m||f,"undefined"===l||"function"===l){b=!b.length&&
d.length?["notrequirebecasebrowserifymessesup","exports","module"]:b;for(l=0;l<b.length;l+=1)if(x=q(b[l],m),w=x.f,"notrequirebecasebrowserifymessesup"===w)H[l]=A.notrequirebecasebrowserifymessesup(f);else if("exports"===w)H[l]=A.exports(f),D=!0;else if("module"===w)u=H[l]=A.module(f);else if(E.call(e,w)||E.call(c,w)||E.call(y,w))H[l]=h(w);else{if(!x.p)throw Error(f+" missing "+w);x.p.load(x.n,t(m,!0),g(w),{});H[l]=e[w]}b=d?d.apply(e[f],H):void 0;f&&(u&&u.exports!==a&&u.exports!==e[f]?e[f]=u.exports:
b===a&&D||(e[f]=b))}else f&&(e[f]=d)};d=n=C=function(c,e,b,t,g){if("string"==typeof c)return A[c]?A[c](e):h(q(c,e).f);if(!c.splice){if(f=c,f.deps&&C(f.deps,f.callback),!e)return;e.splice?(c=e,e=b,b=null):c=a}return e=e||function(){},"function"==typeof b&&(b=t,t=g),t?x(a,c,e,b):setTimeout(function(){x(a,c,e,b)},4),C};C.config=function(c){return C(c)};d._defined=e;l=function(f,q,a){if("string"!=typeof f)throw Error("See almond README: incorrect module build, no module name");q.splice||(a=q,q=[]);E.call(e,
f)||E.call(c,f)||(c[f]=[f,q,a])};l.amd={jQuery:!0}}(),l("node_modules/almond/almond.js",function(){}),l("twgl/typedarrays",[],function(){return{getGLTypeForTypedArray:function(a){if(a instanceof Int8Array)return 5120;if(a instanceof Uint8Array||a instanceof Uint8ClampedArray)return 5121;if(a instanceof Int16Array)return 5122;if(a instanceof Uint16Array)return 5123;if(a instanceof Int32Array)return 5124;if(a instanceof Uint32Array)return 5125;if(a instanceof Float32Array)return 5126;throw"unsupported typed array type";
},getTypedArrayTypeForGLType:function(a){switch(a){case 5120:return Int8Array;case 5121:return Uint8Array;case 5122:return Int16Array;case 5123:return Uint16Array;case 5124:return Int32Array;case 5125:return Uint32Array;case 5126:return Float32Array;default:throw"unknown gl type";}},isArrayBuffer:function(a){return a&&a.buffer&&a.buffer instanceof ArrayBuffer}}}),l("twgl/utils",[],function(){var a=window.console&&window.console.error&&"function"==typeof window.console.error?window.console.error.bind(window.console):
function(){},d=window.console&&window.console.warn&&"function"==typeof window.console.warn?window.console.warn.bind(window.console):function(){};return{copyExistingProperties:function(a,d){Object.keys(d).forEach(function(g){d.hasOwnProperty(g)&&a.hasOwnProperty(g)&&(d[g]=a[g])})},copyNamedProperties:function(a,d,g){a.forEach(function(a){var b=d[a];void 0!==b&&(g[a]=b)})},shallowCopy:function(a){var d={};return Object.keys(a).forEach(function(g){d[g]=a[g]}),d},isWebGL1:function(a){a=parseFloat(a.getParameter(a.VERSION).substr(6));
return 1>=a&&0<a},isWebGL2:function(a){return 0===a.getParameter(a.VERSION).indexOf("WebGL 2.0")},error:a,warn:d}}),l("twgl/attributes",["./typedarrays","./utils"],function(a,d){function t(a,b,e,c){if(b instanceof WebGLBuffer)return b;e=e||a.ARRAY_BUFFER;var f=a.createBuffer();a.bindBuffer(e,f);a.bufferData(e,b,c||a.STATIC_DRAW);return f}function l(a){return a.length?a:a.data}function g(a,b){var e;if(!(e=a.numComponents||a.size)){e=l(a).length;var c;if(c=0<=b.indexOf("coord")?2:0<=b.indexOf("color")?
4:3,0<e%c)throw"can not guess numComponents. You should specify it.";e=c}return e}function h(b,h){if(a.isArrayBuffer(b))return b;if(a.isArrayBuffer(b.data))return b.data;Array.isArray(b)&&(b={data:b});var e=b.type;return e||(e="indices"===h?Uint16Array:Float32Array),new e(b.data)}function b(b,d){var e={};return Object.keys(d).forEach(function(c){if("indices"!==c){var f=d[c],u=f.attrib||f.name||f.attribName||x.attribPrefix+c,l=h(f,c);e[u]={buffer:t(b,l,void 0,f.drawType),numComponents:g(f,c),type:a.getGLTypeForTypedArray(l),
normalize:void 0!==f.normalize?f.normalize:l instanceof Int8Array||l instanceof Uint8Array,stride:f.stride||0,offset:f.offset||0,drawType:f.drawType}}}),e}function u(a,b,e){var c="indices"===e?a.ELEMENT_ARRAY_BUFFER:a.ARRAY_BUFFER;b=h(b,e);return t(a,b,c)}var x={attribPrefix:""},n=function(){var a=["position","positions","a_position"];return function(b){for(var e,c=0;c<a.length&&(e=a[c],!(e in b));++c);c===a.length&&(e=Object.keys(b)[0]);c=b[e];b=l(c).length;e=g(c,e);if(0<b%e)throw"numComponents "+
e+" not correct for length "+b;return b/e}}();return{createAttribsFromArrays:b,createBuffersFromArrays:function(a,b){var e={};return Object.keys(b).forEach(function(c){e[c]=u(a,b[c],c)}),e},createBufferFromArray:u,createBufferFromTypedArray:t,createBufferInfoFromArrays:function(d,g){var e={attribs:b(d,g)},c=g.indices;return c?(c=h(c,"indices"),e.indices=t(d,c,d.ELEMENT_ARRAY_BUFFER),e.numElements=c.length,e.elementType=a.getGLTypeForTypedArray(c)):e.numElements=n(g),e},setAttribInfoBufferFromArray:function(a,
b,e,c){e=h(e);if(c)a.bindBuffer(a.ARRAY_BUFFER,b.buffer),a.bufferSubData(a.ARRAY_BUFFER,c,e);else{c=a.ARRAY_BUFFER;var f=b.drawType;a.bindBuffer(c,b.buffer);a.bufferData(c,e,f||a.STATIC_DRAW)}},createVertexArrayInfo:function(a,b,e){var c=a.createVertexArray();return a.bindVertexArray(c),b.length||(b=[b]),b.forEach(function(c){twgl.setBuffersAndAttributes(a,c,e)}),a.bindVertexArray(null),{numElements:e.numElements,elementType:e.elementType,vertexArrayObject:c}},setAttributePrefix:function(a){x.attribPrefix=
a},setDefaults_:function(a){d.copyExistingProperties(a,x)},getNumComponents_:g,getArray_:l}}),l("twgl/programs",["./utils"],function(a){function d(D,c){return function(a){D.uniform1i(c,a)}}function l(D,c){return function(a){D.uniform1iv(c,a)}}function n(c,a){return function(b){c.uniform2iv(a,b)}}function g(c,a){return function(b){c.uniform3iv(a,b)}}function h(c,a){return function(b){c.uniform4iv(a,b)}}function b(c,a,b,f){var e=m[a].bindPoint;return function(a){c.uniform1i(f,b);c.activeTexture(c.TEXTURE0+
b);c.bindTexture(e,a)}}function u(c,a,b,f,e){var d=m[a].bindPoint,p=new Int32Array(e);for(a=0;a<e;++a)p[a]=b+a;return function(a){c.uniform1iv(f,p);a.forEach(function(a,b){c.activeTexture(c.TEXTURE0+p[b]);c.bindTexture(d,a)})}}function x(a,c){return c=c||0,++c,a.split("\n").map(function(a,b){return b+c+": "+a}).join("\n")}function C(a,c,b,f){f=f||N;b=a.createShader(b);var e=0;F.test(c)&&(e=1,c=c.replace(F,""));a.shaderSource(b,c);a.compileShader(b);if(!a.getShaderParameter(b,a.COMPILE_STATUS)){var d=
a.getShaderInfoLog(b);return f(x(c,e)+"\n*** Error compiling shader: "+d),a.deleteShader(b),null}return b}function q(a,c,b,f,e){"function"==typeof f&&(e=f,f=void 0);"function"==typeof b&&(e=b,b=void 0);e=e||N;var d=a.createProgram();c.forEach(function(p){a.attachShader(d,p)});b&&b.forEach(function(p,c){a.bindAttribLocation(d,f?f[c]:c,p)});a.linkProgram(d);return a.getProgramParameter(d,a.LINK_STATUS)?d:(c=a.getProgramInfoLog(d),e("Error in program linking:"+c),a.deleteProgram(d),null)}function A(a,
c,b,f,e){for(var d=[],p=0;p<c.length;++p){var z=C(a,c[p],a[J[p]],e);if(!z)return null;d.push(z)}return q(a,d,b,f,e)}function e(a,c){for(var b=0,f={},e=a.getProgramParameter(c,a.ACTIVE_UNIFORMS),d=0;d<e;++d){var p=a.getActiveUniform(c,d);if(!p)break;var z=p.name;"[0]"===z.substr(-3)&&(z=z.substr(0,z.length-3));var v=a.getUniformLocation(c,p.name),B=1<p.size&&"[0]"===p.name.substr(-3),R=p.type,G=m[R];if(!G)throw"unknown type: 0x"+R.toString(16);if(G.bindPoint)var h=b,p=(b+=p.size,B?G.arraySetter(a,
R,h,v,p.size):G.setter(a,R,h,v,p.size));else p=G.arraySetter&&B?G.arraySetter(a,v):G.setter(a,v);f[z]=p}return f}function c(a,c){for(var b=a.getProgramParameter(c,a.ACTIVE_UNIFORMS),f=[],e=[],d=0;d<b;++d){e.push(d);f.push({});var p=a.getActiveUniform(c,d);if(!p)break;f[d].name=p.name}[["UNIFORM_TYPE","type"],["UNIFORM_SIZE","size"],["UNIFORM_BLOCK_INDEX","blockNdx"],["UNIFORM_OFFSET","offset"]].forEach(function(p){var b=p[1];a.getActiveUniforms(c,e,a[p[0]]).forEach(function(p,a){f[a][b]=p})});b={};
p=a.getProgramParameter(c,a.ACTIVE_UNIFORM_BLOCKS);for(d=0;d<p;++d){var z=a.getActiveUniformBlockName(c,d),v={index:d,usedByVertexShader:a.getActiveUniformBlockParameter(c,d,a.UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER),usedByFragmentShader:a.getActiveUniformBlockParameter(c,d,a.UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER),size:a.getActiveUniformBlockParameter(c,d,a.UNIFORM_BLOCK_DATA_SIZE),uniformIndices:a.getActiveUniformBlockParameter(c,d,a.UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES)};v.used=v.usedByVertexSahder||
v.usedByFragmentShader;b[z]=v}return{blockSpecs:b,uniformData:f}}function f(a,c,b,f){var e=b.uniformData;b=b.blockSpecs[f];if(!b)return P("no uniform block object named:",f),{name:f,uniforms:{}};var d=new ArrayBuffer(b.size),p=a.createBuffer(),z=b.index;a.bindBuffer(a.UNIFORM_BUFFER,p);a.uniformBlockBinding(c,b.index,z);var v=f+".";Q.test(v)&&(v=v.replace(Q,"."));var B={};return b.uniformIndices.forEach(function(p){p=e[p];var a=m[p.type],c=a.Type,a=p.size*a.size,b=p.name;b.substr(0,v.length)===v&&
(b=b.substr(v.length));B[b]=new c(d,p.offset,a/c.BYTES_PER_ELEMENT)}),{name:f,array:d,asFloat:new Float32Array(d),buffer:p,uniforms:B}}function y(a,c,b){return(c=(c.uniformBlockSpec||c).blockSpecs[b.name])?(a.bindBufferRange(a.UNIFORM_BUFFER,c.index,b.buffer,b.offset||0,b.array.byteLength),!0):!1}function E(a,c){for(var b=a.uniformSetters||a,f=arguments.length,e=1;e<f;++e){var d=arguments[e];if(Array.isArray(d))for(var p=d.length,z=0;z<p;++z)E(b,d[z]);else for(var v in d)(p=b[v])&&p(d[v])}}function I(a,
c){function b(p){return function(c){a.bindBuffer(a.ARRAY_BUFFER,c.buffer);a.enableVertexAttribArray(p);a.vertexAttribPointer(p,c.numComponents||c.size,c.type||a.FLOAT,c.normalize||!1,c.stride||0,c.offset||0)}}function f(p,c){var b=c.size,v=c.count;return function(c){a.bindBuffer(a.ARRAY_BUFFER,c.buffer);var f=c.size||c.numComponents||b,e=f/v,z=c.type||a.FLOAT,f=m[z].size*f,B=c.normalize||!1;c=c.offset||0;for(var d=f/v,h=0;h<v;++h)a.enableVertexAttribArray(p+h),a.vertexAttribPointer(p+h,e,z,B,f,c+
d*h)}}for(var e={},d=a.getProgramParameter(c,a.ACTIVE_ATTRIBUTES),p=0;p<d;++p){var z=a.getActiveAttrib(c,p);if(!z)break;var v=a.getAttribLocation(c,z.name),B=S[z.type];B?e[z.name]=f(v,B):e[z.name]=b(v)}return e}function L(a,c){for(var b in c){var f=a[b];f&&f(c[b])}}function r(b,f){var d=e(b,f),h=I(b,f),d={program:f,uniformSetters:d,attribSetters:h};return a.isWebGL2(b)&&(d.uniformBlockSpec=c(b,f)),d}var N=a.error,P=a.warn,m={};m[5126]={Type:Float32Array,size:4,setter:function(a,c){return function(b){a.uniform1f(c,
b)}},arraySetter:function(a,c){return function(b){a.uniform1fv(c,b)}}};m[35664]={Type:Float32Array,size:8,setter:function(a,c){return function(b){a.uniform2fv(c,b)}}};m[35665]={Type:Float32Array,size:12,setter:function(a,c){return function(b){a.uniform3fv(c,b)}}};m[35666]={Type:Float32Array,size:16,setter:function(a,c){return function(b){a.uniform4fv(c,b)}}};m[5124]={Type:Int32Array,size:4,setter:d,arraySetter:l};m[35667]={Type:Int32Array,size:8,setter:n};m[35668]={Type:Int32Array,size:12,setter:g};
m[35669]={Type:Int32Array,size:16,setter:h};m[5125]={Type:Uint32Array,size:4,setter:function(a,c){return function(b){a.uniform1ui(c,b)}},arraySetter:function(a,c){return function(b){a.uniform1uiv(c,b)}}};m[36294]={Type:Uint32Array,size:8,setter:function(a,c){return function(b){a.uniform2uiv(c,b)}}};m[36295]={Type:Uint32Array,size:12,setter:function(a,c){return function(b){a.uniform3uiv(c,b)}}};m[36296]={Type:Uint32Array,size:16,setter:function(a,c){return function(b){a.uniform4uiv(c,b)}}};m[35670]=
{Type:Uint32Array,size:4,setter:d,arraySetter:l};m[35671]={Type:Uint32Array,size:8,setter:n};m[35672]={Type:Uint32Array,size:12,setter:g};m[35673]={Type:Uint32Array,size:16,setter:h};m[35674]={Type:Float32Array,size:16,setter:function(a,c){return function(b){a.uniformMatrix2fv(c,!1,b)}}};m[35675]={Type:Float32Array,size:36,setter:function(a,c){return function(b){a.uniformMatrix3fv(c,!1,b)}}};m[35676]={Type:Float32Array,size:64,setter:function(a,c){return function(b){a.uniformMatrix4fv(c,!1,b)}}};
m[35685]={Type:Float32Array,size:24,setter:function(a,c){return function(b){a.uniformMatrix2x3fv(c,!1,b)}}};m[35686]={Type:Float32Array,size:32,setter:function(a,c){return function(b){a.uniformMatrix2x4fv(c,!1,b)}}};m[35687]={Type:Float32Array,size:24,setter:function(a,c){return function(b){a.uniformMatrix3x2fv(c,!1,b)}}};m[35688]={Type:Float32Array,size:48,setter:function(a,c){return function(b){a.uniformMatrix3x4fv(c,!1,b)}}};m[35689]={Type:Float32Array,size:32,setter:function(a,c){return function(b){a.uniformMatrix4x2fv(c,
!1,b)}}};m[35690]={Type:Float32Array,size:48,setter:function(a,c){return function(b){a.uniformMatrix4x3fv(c,!1,b)}}};m[35678]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:3553};m[35680]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:34067};m[35679]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:32879};m[35682]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:3553};m[36289]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:35866};m[36292]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:35866};
m[36293]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:34067};m[36298]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:3553};m[36299]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:32879};m[36300]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:34067};m[36303]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:35866};m[36306]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:3553};m[36307]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:32879};m[36308]={Type:null,size:0,setter:b,
arraySetter:u,bindPoint:34067};m[36311]={Type:null,size:0,setter:b,arraySetter:u,bindPoint:35866};var S={35674:{size:4,count:2},35675:{size:9,count:3},35676:{size:16,count:4}},F=/^[ \t]*\n/,J=["VERTEX_SHADER","FRAGMENT_SHADER"],Q=/\[\d+\]\.$/;return{createAttributeSetters:I,createProgram:q,createProgramFromScripts:function(a,c,b,f,e){for(var d=[],p=0;p<c.length;++p){var z;z=a;var v=c[p],B=a[J[p]],h=e,G=void 0,g=document.getElementById(v);if(!g)throw"*** Error: unknown script element"+v;if(v=g.text,
!B)if("x-shader/x-vertex"===g.type)G=z.VERTEX_SHADER;else if("x-shader/x-fragment"===g.type)G=z.FRAGMENT_SHADER;else if(G!==z.VERTEX_SHADER&&G!==z.FRAGMENT_SHADER)throw"*** Error: unknown shader type";z=C(z,v,B?B:G,h);if(!z)return null;d.push(z)}return q(a,d,b,f,e)},createProgramFromSources:A,createProgramInfo:function(a,c,b,f,e){"function"==typeof f&&(e=f,f=void 0);"function"==typeof b&&(e=b,b=void 0);var d=e||N,p=!0;return(c=c.map(function(a){if(0>a.indexOf("\n")){var c=document.getElementById(a);
c?a=c.text:(d("no element with id: "+a),p=!1)}return a}),p)?(c=A(a,c,b,f,e))?r(a,c):null:null},createProgramInfoFromProgram:r,createUniformSetters:e,createUniformBlockSpecFromProgram:c,createUniformBlockInfoFromProgram:f,createUniformBlockInfo:function(a,c,b){return f(a,c.program,c.uniformBlockSpec,b)},setAttributes:L,setBuffersAndAttributes:function(a,c,b){b.vertexArrayObject?a.bindVertexArray(b.vertexArrayObject):(L(c.attribSetters||c,b.attribs),b.indices&&a.bindBuffer(a.ELEMENT_ARRAY_BUFFER,b.indices))},
setUniforms:E,setUniformBlock:function(a,c,b){y(a,c,b)&&a.bufferData(a.UNIFORM_BUFFER,b.array,a.DYNAMIC_DRAW)},setBlockUniforms:function(a,c){var b=a.uniforms,f;for(f in c){var e=b[f];if(e){var d=c[f];d.length?e.set(d):e[0]=d}}},bindUniformBlock:y}}),l("twgl/draw",["./programs"],function(a){function d(a,l,g,h,b){var u=g.indices,x=g.elementType;h=void 0===h?g.numElements:h;b=void 0===b?0:b;x||u?a.drawElements(l,h,void 0===x?a.UNSIGNED_SHORT:g.elementType,b):a.drawArrays(l,b,h)}return{drawBufferInfo:d,
drawObjectList:function(l,n){var g=null,h=null;n.forEach(function(b){if(!1!==b.active){var u=b.programInfo,x=b.vertexArrayInfo||b.bufferInfo,n=!1,q=void 0===b.type?l.TRIANGLES:b.type;u!==g&&(g=u,l.useProgram(u.program),n=!0);(n||x!==h)&&(h&&h.vertexArrayObject&&!x.vertexArrayObject&&l.bindVertexArray(null),h=x,a.setBuffersAndAttributes(l,u,x));a.setUniforms(u,b.uniforms);d(l,q,x,b.count,b.offset)}});h.vertexArrayObject&&l.bindVertexArray(null)}}}),l("twgl/textures",["./typedarrays","./utils"],function(a,
d){var l,n,g;function h(a){F.textureColor=new Uint8Array([255*a[0],255*a[1],255*a[2],255*a[3]])}function b(a,c){void 0!==c.colorspaceConversion&&(l=a.getParameter(a.UNPACK_COLORSPACE_CONVERSION_WEBGL),a.pixelStorei(a.UNPACK_COLORSPACE_CONVERSION_WEBGL,c.colorspaceConversion));void 0!==c.premultiplyAlpha&&(n=a.getParameter(a.UNPACK_PREMULTIPLY_ALPHA_WEBGL),a.pixelStorei(a.UNPACK_PREMULTIPLY_ALPHA_WEBGL,c.premultiplyAlpha));void 0!==c.flipY&&(g=a.getParameter(a.UNPACK_FLIP_Y_WEBGL),a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,
c.flipY))}function u(a,c){void 0!==c.colorspaceConversion&&a.pixelStorei(a.UNPACK_COLORSPACE_CONVERSION_WEBGL,l);void 0!==c.premultiplyAlpha&&a.pixelStorei(a.UNPACK_PREMULTIPLY_ALPHA_WEBGL,n);void 0!==c.flipY&&a.pixelStorei(a.UNPACK_FLIP_Y_WEBGL,g)}function x(a,c,b){var f=b.target||a.TEXTURE_2D;a.bindTexture(f,c);b.min&&a.texParameteri(f,a.TEXTURE_MIN_FILTER,b.min);b.mag&&a.texParameteri(f,a.TEXTURE_MAG_FILTER,b.mag);b.wrap&&(a.texParameteri(f,a.TEXTURE_WRAP_S,b.wrap),a.texParameteri(f,a.TEXTURE_WRAP_T,
b.wrap),f===a.TEXTURE_3D&&a.texParameteri(f,a.TEXTURE_WRAP_R,b.wrap));b.wrapR&&a.texParameteri(f,a.TEXTURE_WRAP_R,b.wrapR);b.wrapS&&a.texParameteri(f,a.TEXTURE_WRAP_S,b.wrapS);b.wrapT&&a.texParameteri(f,a.TEXTURE_WRAP_T,b.wrapT);b.minLod&&a.texParameteri(f,a.TEXTURE_MIN_LOD,b.minLod);b.maxLod&&a.texParameteri(f,a.TEXTURE_MAX_LOD,b.maxLod);b.baseLevel&&a.texParameteri(f,a.TEXTURE_BASE_LEVEL,b.baseLevel);b.maxLevel&&a.texParameteri(f,a.TEXTURE_MAX_LEVEL,b.maxLevel)}function C(a,c,b,f,e){b=b||F.textureOptions;
var d=b.target||a.TEXTURE_2D;f=f||b.width;e=e||b.height;a.bindTexture(d,c);0===(f&f-1)&&0===(e&e-1)?a.generateMipmap(d):(a.texParameteri(d,a.TEXTURE_MIN_FILTER,a.LINEAR),a.texParameteri(d,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE),a.texParameteri(d,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE))}function q(a,c){return c=c||{},c.cubeFaceOrder||[a.TEXTURE_CUBE_MAP_POSITIVE_X,a.TEXTURE_CUBE_MAP_NEGATIVE_X,a.TEXTURE_CUBE_MAP_POSITIVE_Y,a.TEXTURE_CUBE_MAP_NEGATIVE_Y,a.TEXTURE_CUBE_MAP_POSITIVE_Z,a.TEXTURE_CUBE_MAP_NEGATIVE_Z]}
function A(a,c){var b=q(a,c).map(function(a,c){return{face:a,ndx:c}});return b.sort(function(a,c){return a.face-c.face}),b}function e(){}function c(a,c,b){function f(){g.removeEventListener("error",h);g.removeEventListener("load",l);g=null}function h(){var c="couldn't load image: "+a;d.error(c);b(c,g);f()}function l(){b(null,g);f()}b=b||e;var g=new Image;return c=void 0!==c?c:F.crossOrigin,void 0!==c&&(g.crossOrigin=c),g.addEventListener("error",h),g.addEventListener("load",l),g.src=a,g}function f(a,
c,b){b=b||F.textureOptions;var f=b.target||a.TEXTURE_2D;if(a.bindTexture(f,c),!1!==b.color)if(b=b.color,c=(b=b||F.textureColor,J(b)?b:new Uint8Array([255*b[0],255*b[1],255*b[2],255*b[3]])),f===a.TEXTURE_CUBE_MAP)for(f=0;6>f;++f)a.texImage2D(a.TEXTURE_CUBE_MAP_POSITIVE_X+f,0,a.RGBA,1,1,0,a.RGBA,a.UNSIGNED_BYTE,c);else f===a.TEXTURE_3D?a.texImage3D(f,0,a.RGBA,1,1,1,0,a.RGBA,a.UNSIGNED_BYTE,c):a.texImage2D(f,0,a.RGBA,1,1,0,a.RGBA,a.UNSIGNED_BYTE,c)}function y(a,b,v,B){B=B||e;v=v||F.textureOptions;f(a,
b,v);v=d.shallowCopy(v);return c(v.src,v.crossOrigin,function(c,f){c?B(c,b,f):(K(a,b,f,v),B(null,b,f))})}function E(a,z,v,B){function h(c){return function(f,e){--r;f?y.push(f):e.width!==e.height?y.push("cubemap face img is not a square: "+e.src):(b(a,v),a.bindTexture(n,z),5===r?q(a).forEach(function(c){a.texImage2D(c,0,l,l,m,e)}):a.texImage2D(c,0,l,l,m,e),u(a,v),a.generateMipmap(n));0===r&&B(y.length?y:void 0,x,z)}}B=B||e;var g=v.src;if(6!==g.length)throw"there must be 6 urls for a cubemap";var l=
v.format||a.RGBA,m=v.type||a.UNSIGNED_BYTE,n=v.target||a.TEXTURE_2D;if(n!==a.TEXTURE_CUBE_MAP)throw"target must be TEXTURE_CUBE_MAP";f(a,z,v);v=d.shallowCopy(v);var x,r=6,y=[],t=q(a,v);x=g.map(function(a,b){return c(a,v.crossOrigin,h(t[b]))})}function I(a){switch(a){case Q:case O:return 1;case T:return 2;case D:return 3;case H:return 4;default:throw"unknown type: "+a;}}function L(c,b){return J(b)?a.getGLTypeForTypedArray(b):c.UNSIGNED_BYTE}function r(a,c,b,f,e){if(0!==e%1)throw"can't guess dimensions";
if(b||f)if(f){if(!b&&(b=e/f,b%1))throw"can't guess dimensions";}else{if(f=e/b,f%1)throw"can't guess dimensions";}else a=Math.sqrt(e/(c===a.TEXTURE_CUBE_MAP?6:1)),0===a%1?(b=a,f=a):(b=e,f=1);return{width:b,height:f}}function N(c,f,e,d){d=d||F.textureOptions;var h=d.target||c.TEXTURE_2D;c.bindTexture(h,f);var g=d.width,l=d.height,m=d.depth,n=d.format||c.RGBA,x=d.internalFormat||n,q=d.type||L(c,e);f=I(n);var y=e.length/f;if(y%1)throw"length wrong size for format: "+U(c,n);var t;if(h===c.TEXTURE_3D)if(g||
l||m)!g||l&&m?!l||g&&m?(t=r(c,h,g,l,y/m),g=t.width,l=t.height):(t=r(c,h,g,m,y/l),g=t.width,m=t.height):(t=r(c,h,l,m,y/g),l=t.width,m=t.height);else{t=Math.cbrt(y);if(0!==t%1)throw"can't guess cube size of array of numElements: "+y;m=l=g=t}else t=r(c,h,g,l,y),g=t.width,l=t.height;J(e)?e instanceof Uint8ClampedArray&&(e=new Uint8Array(e.buffer)):e=new (a.getTypedArrayTypeForGLType(q))(e);if(c.pixelStorei(c.UNPACK_ALIGNMENT,d.unpackAlignment||1),b(c,d),h===c.TEXTURE_CUBE_MAP){var w=y/6*f;A(c,d).forEach(function(a){var b=
w*a.ndx,b=e.subarray(b,b+w);c.texImage2D(a.face,0,x,g,l,0,n,q,b)})}else h===c.TEXTURE_3D?c.texImage3D(h,0,x,g,l,m,0,n,q,e):c.texImage2D(h,0,x,g,l,0,n,q,e);return u(c,d),{width:g,height:l,depth:m}}function P(a,c,f){var e=f.target||a.TEXTURE_2D;a.bindTexture(e,c);c=f.format||a.RGBA;var d=f.internalFormat||c,h=f.type||a.UNSIGNED_BYTE;if(b(a,f),e===a.TEXTURE_CUBE_MAP)for(e=0;6>e;++e)a.texImage2D(a.TEXTURE_CUBE_MAP_POSITIVE_X+e,0,d,f.width,f.height,0,c,h,null);else e===a.TEXTURE_3D?a.texImage3D(e,0,d,
f.width,f.height,f.depth,0,c,h,null):a.texImage2D(e,0,d,f.width,f.height,0,c,h,null);u(a,f)}function m(a,c,b){b=b||e;c=c||F.textureOptions;var f=a.createTexture(),d=c.target||a.TEXTURE_2D,h=c.width||1,g=c.height||1;a.bindTexture(d,f);d===a.TEXTURE_CUBE_MAP&&(a.texParameteri(d,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE),a.texParameteri(d,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE));if(d=c.src)if("function"==typeof d&&(d=d(a,c)),"string"==typeof d)y(a,f,c,b);else if(J(d)||Array.isArray(d)&&("number"==typeof d[0]||Array.isArray(d[0])||
J(d[0])))b=N(a,f,d,c),h=b.width,g=b.height;else if(Array.isArray(d)&&"string"==typeof d[0])E(a,f,c,b);else{if(!(d instanceof HTMLElement))throw"unsupported src type";K(a,f,d,c);h=d.width;g=d.height}else P(a,f,c);return!1!==c.auto&&C(a,f,c,h,g),x(a,f,c),f}function S(a){return"string"==typeof a||Array.isArray(a)&&"string"==typeof a[0]}var F={textureColor:new Uint8Array([128,192,255,255]),textureOptions:{},crossOrigin:void 0},J=a.isArrayBuffer,Q=6406,D=6407,H=6408,O=6409,T=6410,U=function(){function a(b){c||
(c={},Object.keys(b).forEach(function(a){"number"==typeof b[a]&&(c[b[a]]=a)}))}var c;return function(b,f){return a(),c[f]||"0x"+f.toString(16)}}();g=n=l=void 0;var K=function(){var a=document.createElement("canvas").getContext("2d");return function(c,f,e,d){d=d||F.textureOptions;var h=d.target||c.TEXTURE_2D,g=e.width,l=e.height,m=d.format||c.RGBA,n=d.internalFormat||m,t=d.type||c.UNSIGNED_BYTE;if(b(c,d),c.bindTexture(h,f),h===c.TEXTURE_CUBE_MAP){var y,q,h=e.width,g=e.height;if(h/6===g)y=g,q=[0,0,
1,0,2,0,3,0,4,0,5,0];else if(g/6===h)y=h,q=[0,0,0,1,0,2,0,3,0,4,0,5];else if(h/3===g/2)y=h/3,q=[0,0,1,0,2,0,0,1,1,1,2,1];else{if(h/2!==g/3)throw"can't figure out cube map from element: "+(e.src?e.src:e.nodeName);y=h/2;q=[0,0,1,0,0,1,1,1,0,2,1,2]}a.canvas.width=y;l=g=a.canvas.height=y;A(c,d).forEach(function(b){a.drawImage(e,q[2*b.ndx+0]*y,q[2*b.ndx+1]*y,y,y,0,0,y,y);c.texImage2D(b.face,0,n,m,t,a.canvas)});a.canvas.width=1;a.canvas.height=1}else if(h===c.TEXTURE_3D){var r=Math.min(e.width,e.height),
w=Math.max(e.width,e.height),E=w/r;if(0!==E%1)throw"can not compute 3D dimensions of element";var I=e.width===w?1:0,w=e.height===w?1:0;c.texImage3D(h,0,n,r,r,r,0,m,t,null);a.canvas.width=r;a.canvas.height=r;for(var D=0;D<E;++D)a.drawImage(e,D*r*I,D*r*w,r,r,0,0,r,r),c.texSubImage3D(h,0,0,0,D,m,t,a.canvas);a.canvas.width=0;a.canvas.height=0}else c.texImage2D(h,0,n,m,t,e);u(c,d);!1!==d.auto&&C(c,f,d,g,l);x(c,f,d)}}();return{setDefaults_:function(a){d.copyExistingProperties(a,F);a.textureColor&&h(a.textureColor)},
createTexture:m,setEmptyTexture:P,setTextureFromArray:N,loadTextureFromUrl:y,setTextureFromElement:K,setTextureFilteringForSize:C,setTextureParameters:x,setDefaultTextureColor:h,createTextures:function(a,c,b){function f(){0===d&&setTimeout(function(){b(h.length?h:void 0,g,l)},0)}b=b||e;var d=0,h=[],g={},l={};return Object.keys(c).forEach(function(b){var e,y=c[b];S(y.src)&&(e=function(a,c,e){l[b]=e;--d;a&&h.push(a);f()},++d);g[b]=m(a,y,e)}),f(),g},resizeTexture:function(a,c,b,f,e){f=f||b.width;e=e||
b.height;var d=b.target||a.TEXTURE_2D;a.bindTexture(d,c);c=b.format||a.RGBA;var h=b.src;if(b=h&&(J(h)||Array.isArray(h)&&"number"==typeof h[0])?b.type||L(a,h):b.type||a.UNSIGNED_BYTE,d===a.TEXTURE_CUBE_MAP)for(d=0;6>d;++d)a.texImage2D(a.TEXTURE_CUBE_MAP_POSITIVE_X+d,0,c,f,e,0,c,b,null);else a.texImage2D(d,0,c,f,e,0,c,b,null)},getNumComponentsForFormat:I}}),l("twgl/framebuffers",["./textures","./utils"],function(a,d){var l=[{format:6408,type:5121,min:9729,wrap:33071},{format:34041}],n={34041:33306,
6401:36128,36168:36128,6402:36096,33189:36096},g={};return g[32854]=!0,g[32855]=!0,g[36194]=!0,g[34041]=!0,g[33189]=!0,g[6401]=!0,g[36168]=!0,{bindFramebufferInfo:function(a,b,d){d=d||a.FRAMEBUFFER;b?(a.bindFramebuffer(d,b.framebuffer),a.viewport(0,0,b.width,b.height)):(a.bindFramebuffer(d,null),a.viewport(0,0,a.drawingBufferWidth,a.drawingBufferHeight))},createFramebufferInfo:function(h,b,u,x){var C=h.FRAMEBUFFER,q=h.createFramebuffer();h.bindFramebuffer(C,q);u=u||h.drawingBufferWidth;x=x||h.drawingBufferHeight;
b=b||l;var A=0,e={framebuffer:q,attachments:[],width:u,height:x};return b.forEach(function(c){var b=c.attachment,l=c.format,q=n[l];(q||(q=36064+A++),b)||(g[l]?(b=h.createRenderbuffer(),h.bindRenderbuffer(h.RENDERBUFFER,b),h.renderbufferStorage(h.RENDERBUFFER,l,u,x)):(b=d.shallowCopy(c),b.width=u,b.height=x,void 0===b.auto&&(b.auto=!1,b.min=b.min||h.LINEAR,b.mag=b.mag||h.LINEAR,b.wrapS=b.wrapS||b.wrap||h.CLAMP_TO_EDGE,b.wrapT=b.wrapT||b.wrap||h.CLAMP_TO_EDGE),b=a.createTexture(h,b)));if(b instanceof
WebGLRenderbuffer)h.framebufferRenderbuffer(C,q,h.RENDERBUFFER,b);else{if(!(b instanceof WebGLTexture))throw"unknown attachment type";h.framebufferTexture2D(C,q,c.texTarget||h.TEXTURE_2D,b,c.level||0)}e.attachments.push(b)}),e},resizeFramebufferInfo:function(d,b,g,n,w){n=n||d.drawingBufferWidth;w=w||d.drawingBufferHeight;b.width=n;b.height=w;g=g||l;g.forEach(function(g,l){var e=b.attachments[l],c=g.format;if(e instanceof WebGLRenderbuffer)d.bindRenderbuffer(d.RENDERBUFFER,e),d.renderbufferStorage(d.RENDERBUFFER,
c,n,w);else{if(!(e instanceof WebGLTexture))throw"unknown attachment type";a.resizeTexture(d,e,g,n,w)}})}}}),l("twgl/twgl","./attributes ./draw ./framebuffers ./programs ./textures ./typedarrays ./utils".split(" "),function(a,d,l,n,g,h,b){function u(a){if(a&&q.enableVertexArrayObjects&&b.isWebGL1(a)){var f=a.getExtension("OES_vertex_array_object");f&&(a.createVertexArray=function(){return f.createVertexArrayOES()},a.deleteVertexArray=function(a){f.deleteVertexArrayOES(a)},a.isVertexArray=function(a){return f.isVertexArrayOES(a)},
a.bindVertexArray=function(a){f.bindVertexArrayOES(a)},a.VERTEX_ARRAY_BINDING=f.VERTEX_ARRAY_BINDING_OES)}}function x(a){return"_"!==a[a.length-1]}function C(a,b){return Object.keys(a).filter(x).forEach(function(d){b[d]=a[d]}),b}var q={enableVertexArrayObjects:!0},A={getContext:function(a,b){var d;d=["webgl2","experimental-webgl2","webgl","experimental-webgl"];for(var e=null,g=0;g<d.length;++g){try{e=a.getContext(d[g],b)}catch(h){}if(e)break}d=e;return u(d),d},getWebGLContext:function(a,b){var d;
d=["webgl","experimental-webgl"];for(var e=null,g=0;g<d.length;++g){try{e=a.getContext(d[g],b)}catch(h){}if(e)break}d=e;return u(d),d},isWebGL1:b.isWebGL1,isWebGL2:b.isWebGL2,resizeCanvasToDisplaySize:function(a,b){b=Math.max(1,b||1);var d=a.clientWidth*b|0,e=a.clientHeight*b|0;return(a.width!==d||a.height!==e)&&(a.width=d,a.height=e,!0)},setDefaults:function(c){b.copyExistingProperties(c,q);a.setDefaults_(c);g.setDefaults_(c)}},e={attributes:a,draw:d,framebuffers:l,programs:n,textures:g,typedArrays:h};
return Object.keys(e).forEach(function(a){var b=e[a];C(b,A);A[a]=C(b,{})}),A}),l("main",["twgl/twgl"],function(a){return a}),n(["main"],function(a){return a},void 0,!0),l("build/js/twgl-includer",function(){}),n("main")});
var Demo=function(d,n){this.renderer=twgl.getWebGLContext(d);this.renderer.getExtension("OES_standard_derivatives");this.programInfo=twgl.createProgramInfo(this.renderer,[this.vertexShader,n?n:this.fragmentShader]);this.bufferInfo=twgl.createBufferInfoFromArrays(this.renderer,{position:[-1,-1,0,1,-1,0,-1,1,0,-1,1,0,1,-1,0,1,1,0]});this.mouse=[0,0]};
Demo.prototype.update=function(d,n){var l=this.renderer;twgl.resizeCanvasToDisplaySize(l.canvas);l.viewport(0,0,l.canvas.width,l.canvas.height);var a={iGlobalTime:d,iResolution:[l.canvas.width,l.canvas.height],iMouse:[0,-.05,0,0],iMusicLow:n.low,iMusicMid:n.mid,iMusicHigh:n.high};l.useProgram(this.programInfo.program);twgl.setBuffersAndAttributes(l,this.programInfo,this.bufferInfo);twgl.setUniforms(this.programInfo,a);twgl.drawBufferInfo(l,l.TRIANGLES,this.bufferInfo)};
Demo.prototype.vertexShader="precision highp float;\nattribute vec3 position;\nvarying vec2 vUv;\nvoid main() {\nvUv = position.xy * 0.5 + 0.5;\ngl_Position = vec4(position.xy,1.0, 1.0 );\n}";Demo.prototype.fragmentShader="precision highp float;\nvarying vec2 vUv;\nuniform float iGlobalTime;\nuniform vec2 iResolution;\nuniform vec4 iMusicLow;\nuniform vec4 iMusicMid;\nuniform vec4 iMusicHigh;\nvoid main () {\n gl_FragColor.rgb =  mix(iMusicMid.rgb, iMusicHigh.bgr, gl_FragCoord.x/iResolution.x);\n gl_FragColor.a = 1.0;\n}";
var danza=new Danza(2048);audio=document.getElementById("audio");danza.listen(audio);var demo=new Demo(document.getElementById("canvas"),document.getElementById("fragment").innerText),funcs={low:danza.spawn({from:10,to:32,smooth:[.2,.2,.2,.2]}),mid:danza.spawn({from:32,to:48,smooth:[.1,.1,.1,.1]}),high:danza.spawn({from:64,to:128,smooth:[.2,.2,.2,.2]})};function play(d){audio.src="audio/"+d+".mp3";audio.play()}
function render(d){window.requestAnimationFrame(render);danza.update();var n={};for(k in funcs)n[k]=funcs[k](d);demo.update(d/1E3,n)}render(0);